/*
-- Query: select * from CM_ADDRESS
LIMIT 0, 1000

-- Date: 2017-01-09 21:35
*/
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('flow1','1楼层','F',1,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('flow10','10楼层','F',10,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('flow2','2楼层','F',2,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('flow3','3楼层','F',3,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('flow4','4楼层','F',4,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('flow5','5楼层','F',5,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('flow6','6楼层','F',6,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('flow7','7楼层','F',7,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('flow8','8楼层','F',8,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('flow9','9楼层','F',9,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('jy1d','菊苑1栋','D',31,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('jy2d','菊苑2栋','D',32,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('jy3d','菊苑3栋','D',33,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('jy4d','菊苑4栋','D',34,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('jy5d','菊苑5栋','D',35,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('ly1d','兰苑1栋','D',21,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('ly2d','兰苑2栋','D',22,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('ly3d','兰苑3栋','D',23,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('ly4d','兰苑4栋','D',24,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('ly5d','兰苑5栋','D',25,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('my10d','梅苑10栋','D',10,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('my1d','梅苑1栋','D',1,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('my2d','梅苑2栋','D',2,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('my3d','梅苑3栋','D',3,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('my4d','梅苑4栋','D',4,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('my5d','梅苑5栋','D',5,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('my6d','梅苑6栋','D',6,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('my7d','梅苑7栋','D',7,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('my8d','梅苑8栋','D',8,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('my9d','梅苑9栋','D',9,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('rx1d','榕轩1栋','D',41,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('rx2d','榕轩2栋','D',42,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('rx3d','榕轩3栋','D',43,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('rx4d','榕轩4栋','D',44,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('rx5d','榕轩5栋','D',45,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('rx6d','榕轩6栋','D',46,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('rx7d','榕轩7栋','D',47,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('rx8d','榕轩8栋','D',48,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('zy1d','竹苑1栋','D',11,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('zy2d','竹苑2栋','D',12,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('zy3d','竹苑3栋','D',13,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('zy4d','竹苑4栋','D',14,'',NULL);
INSERT INTO `CM_ADDRESS` (`ID`,`INFO`,`TYPE_ID`,`SEQ`,`PID`,`NOTE`) VALUES ('zy5d','竹苑5栋','D',15,'',NULL);
